/** English liability waiver — content from client/waiverIngles.pdf */
export const WAIVER_TEXT_EN_HTML = `
<p>With full legal capacity to enter into this instrument and without any defect in my consent, including error, duress, or fraud, I voluntarily and expressly manifest my total agreement with the provisions set forth in the clauses of this instrument, which governs the activities of Parque Barrancas, managed by the legal entity Promotora de Símbolos ¡Ah Chihuahua!, S.C.</p>
<p><strong>1st</strong> The participant in this act recognizes and accepts that they have voluntarily requested to participate in the activities of Parque Barrancas, which include: Treetop Adventure (Bosque Aéreo), Seven-Zipline Circuit (Circuito de Siete Tirolesas), Via Ferrata, and ZipRider. Information regarding these activities is available for consultation prior to your visit, in printed and electronic form, on the website: www.parquebarrancas.com.</p>
<p><strong>2nd</strong> The participant states that they are fully aware that the activities of Parque Barrancas are high-risk and involve inherent dangers (including the possibility of severe injury and/or death) that cannot be eliminated even when all safety, care, prevention, training, or supervision measures are adopted. Therefore, the participant understands the nature and scope of the risks associated with these activities and, freely, voluntarily, and in an informed manner, assumes full responsibility for their participation, recognizing that these risks are inherent to the activity and that their elimination would affect essential qualities of the same.</p>
<p><strong>3rd</strong> Because Parque Barrancas allows the participant to carry out the activities and use its facilities, the participant accepts and declares that they release Parque Barrancas from all liability, as well as its affiliates, partners, employees, agents, contractors, and suppliers, and that neither they nor their heirs, assignees, or legal representatives may bring actions, claims, lawsuits, or attachments, present or future, for injuries, damages, death, or losses arising from their participation in said activities.</p>
<p><strong>4th</strong> The participant accepts and agrees that the terms and conditions of the preceding clauses shall remain in effect and legally binding at all times, and shall be obligatory for their assignees, heirs, beneficiaries, guardians, and legal representatives. Likewise, in the event of any legal action or proceeding, the participant agrees to submit exclusively to the laws of the State of Chihuahua, without applying laws of other jurisdictions, and to submit to the courts of the city of Chihuahua, Chihuahua, Mexico, waiving any other jurisdiction that may apply by reason of their present or future domiciles.</p>
<p><mark><strong>5th</strong> The participant declares that they are not under the influence of alcohol, drugs, or narcotics, nor in a state of pregnancy, that could affect their ability to participate in the activities of Parque Barrancas. They also state that they do not suffer from any of the following conditions nor are they under treatment for them: a. Heart and/or lung disease or condition, b. Low or high blood pressure, c. Fainting or seizures, d. Loss or impairment of sight or hearing, e. Nervous disorders, f. Diabetes, g. Liver or related diseases, h. Shortness of breath, i. Related diseases requiring medical treatment or evaluation, surgeries, or previous injuries, j. Spinal operations. Furthermore, the participant declares that they are not taking medication and have not consumed alcoholic beverages, drugs, or narcotics within the last twelve (12) hours and agrees to submit to the evaluation and restrictions determined by the nursing staff of Parque Barrancas.</mark></p>
<p><strong>6th</strong> The participant declares that they have read and fully understand the content of this document, including all health and safety requirements, and that they assume responsibility for organizing their own travel itinerary. They recognize that this instrument constitutes a civil, criminal, and commercial release of liability entered into freely and voluntarily with Promotora de Símbolos ¡Ah Chihuahua!, S.C. and/or its affiliates and sign it of their own accord. <strong>LIKEWISE, THEY ACCEPT THAT THE MAXIMUM AGE FOR PARTICIPATING IN THE ACTIVITIES IS 84 YEARS (Without exception).</strong></p>
<p><mark><strong>7th</strong> The participant accepts and agrees that, once the activity has begun and from the moment the purchase ticket is issued, no refund of the amount paid shall be granted, even when for reasons beyond Parque Barrancas the activity cannot be carried out under the initially planned terms, including contracted packages, in accordance with the Visitor Regulations and the current Cancellation Policy.</mark></p>
<p><mark><strong>THE PARTICIPANT ACCEPTS THAT THEY HAVE READ AND REVIEWED THIS LIABILITY AGREEMENT IN ITS ENTIRETY AND THAT, UNDER PENALTY OF PERJURY, THEY KNOW, UNDERSTAND, AND ACCEPT THE VISITOR REGULATIONS, THE PRIVACY NOTICE, AND THE CANCELLATION POLICY OF PARQUE BARRANCAS.</strong></mark></p>
<p><strong>ACTIVITY DURATION AND LAST DEPARTURE TIME</strong></p>
<ul>
<li><strong>Treetop Adventure (Bosque Aéreo):</strong> Duration 1–1.5 hours / Last departure: 14:15 h.</li>
<li><strong>Via Ferrata:</strong> Duration 1.5–2.5 hours / Last departure: 14:15 h.</li>
<li><strong>Seven-Zipline Circuit (Circuito de 7 Tirolesas):</strong> Duration 2–2.5 hours / Last departure: 13:30 h.</li>
<li><strong>ZipRider:</strong> Duration 1–1.5 hours / Last departure: 15:30 h.</li>
</ul>
<p><em>Times and schedules may vary depending on visitor volume, weather conditions, or other operational circumstances.</em></p>
<p><strong>HEIGHT AND WEIGHT RESTRICTIONS</strong></p>
<ul>
<li><strong>Treetop Adventure (Bosque Aéreo):</strong> Min. height: 1.50 m / Weight: 40 kg – 80 kg</li>
<li><strong>Via Ferrata:</strong> Min. height: 1.60 m / Weight: 40 kg – 99 kg</li>
<li><strong>Seven-Zipline Circuit (Circuito de 7 Tirolesas):</strong> 1.60 m – 2.00 m / Weight: 45 kg – 118 kg</li>
<li><strong>ZipRider:</strong> Min. height: 1.60 m – 1.90 m / Weight: 45 kg – 99 kg</li>
</ul>
`.trim();
