services:
  - type: web
    name: waiver-app
    runtime: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SUPERADMIN_EMAIL
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        sync: false
